# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Main demo
    before: cp int.go ../example/hello/reverse
    init: | # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
      go run ./hello


# Multi repo. Learn more: https://www.gitpod.io/docs/configure/workspaces/multi-repo
workspaceLocation: template-go-workspaces/main.code-workspace # Relative to /workspace dir
additionalRepositories:
  - url: https://go.googlesource.com/example
    checkoutLocation: example # not really necessary to specify since we're using the same name as the URL.